# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: uniswap-cca-indexer
rollback_on_reorg: false
contracts:
  - name: CCAFactory
    handler: src/factory.ts
    events:
      - event: AuctionCreated(address indexed auction, address indexed token, uint256 amount, bytes configData)
  - name: Auction
    handler: src/auction.ts
    events:
      - event: AuctionStepRecorded(uint256 startBlock, uint256 endBlock, uint24 mps)
      - event: TickInitialized(uint256 price)
      - event: BidSubmitted(uint256 indexed id, address indexed owner, uint256 price, uint128 amount)
        field_selection:
          transaction_fields:
            - "hash"
      - event: CheckpointUpdated(uint256 blockNumber, uint256 clearingPrice, uint24 cumulativeMps)
      - event: BidExited(uint256 indexed bidId, address indexed owner, uint256 tokensFilled, uint256 currencyRefunded)
        field_selection:
          transaction_fields:
            - "hash"
      - event: TokensClaimed(uint256 indexed bidId, address indexed owner, uint256 tokensFilled)
        field_selection:
          transaction_fields:
            - "hash"
      - event: TokensReceived(uint256 totalSupply)
chains:
  - id: 8453
    start_block: 41336765
    contracts:
      - name: CCAFactory
        address:
          - 0xCCccCcCAE7503Cac057829BF2811De42E16e0bD5
  - id: 42161
    start_block: 425561182
    contracts:
      - name: CCAFactory
        address:
          - 0xCCccCcCAE7503Cac057829BF2811De42E16e0bD5
