export const AuctionABI = [
  {
    type: 'function',
    name: 'totalSupply',
    inputs: [],
    outputs: [{ name: '', type: 'uint128', internalType: 'uint128' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'token',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20Minimal' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'currency',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'Currency' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'validationHook',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IValidationHook' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'startBlock',
    inputs: [],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'endBlock',
    inputs: [],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'claimBlock',
    inputs: [],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'floorPrice',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tickSpacing',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pointer',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ticks',
    inputs: [{ name: 'price', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct Tick',
        components: [
          { name: 'next', type: 'uint256', internalType: 'uint256' },
          { name: 'currencyDemandQ96', type: 'uint256', internalType: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'checkpoints',
    inputs: [{ name: 'blockNumber', type: 'uint64', internalType: 'uint64' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct Checkpoint',
        components: [
          { name: 'clearingPrice', type: 'uint256', internalType: 'uint256' },
          { name: 'currencyRaisedAtClearingPriceQ96_X7', type: 'uint256', internalType: 'ValueX7' },
          { name: 'cumulativeMpsPerPrice', type: 'uint256', internalType: 'uint256' },
          { name: 'cumulativeMps', type: 'uint24', internalType: 'uint24' },
          { name: 'prev', type: 'uint64', internalType: 'uint64' },
          { name: 'next', type: 'uint64', internalType: 'uint64' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalCleared',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'currencyRaised',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'clearingPrice',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
] as const;
